// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFZBguQ4iWoAZ-T6tQTd5ChY1jN5cnLGM',
    appId: '1:162940324972:web:85626f6cc2ba67328f1c49',
    messagingSenderId: '162940324972',
    projectId: 'onurun-sky-sky',
    authDomain: 'onurun-sky-sky.firebaseapp.com',
    storageBucket: 'onurun-sky-sky.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRHkmDdbCJXDKzpSey7ywYllLMevQOD3c',
    appId: '1:162940324972:android:a58521c3ed10f4e08f1c49',
    messagingSenderId: '162940324972',
    projectId: 'onurun-sky-sky',
    storageBucket: 'onurun-sky-sky.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk8A6XWXSQZ9wN63yjpOEd1gZ-kt5_8sc',
    appId: '1:162940324972:ios:a18f3c520923f4e08f1c49',
    messagingSenderId: '162940324972',
    projectId: 'onurun-sky-sky',
    storageBucket: 'onurun-sky-sky.appspot.com',
    iosClientId: '162940324972-hhgac9n61j1itd0co77p9orjfl9t2tsp.apps.googleusercontent.com',
    iosBundleId: 'sky.sky.onurun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk8A6XWXSQZ9wN63yjpOEd1gZ-kt5_8sc',
    appId: '1:162940324972:ios:a18f3c520923f4e08f1c49',
    messagingSenderId: '162940324972',
    projectId: 'onurun-sky-sky',
    storageBucket: 'onurun-sky-sky.appspot.com',
    iosClientId: '162940324972-hhgac9n61j1itd0co77p9orjfl9t2tsp.apps.googleusercontent.com',
    iosBundleId: 'sky.sky.onurun',
  );
}
